<?xml version="1.0"?>
<!--
    This is the JJack palette configuration file for the Bean Builder. 
    Originally taken and modified from <beanbuilder>/lib/palette.xml.
-->
<!DOCTYPE palette [
	<!ELEMENT palette (tab+)>
	<!ATTLIST tab name CDATA #REQUIRED>
	<!ELEMENT tab (item+)>
	<!ELEMENT item (#PCDATA)>
]>
<palette>
<tab name="JJack">
	<item>de.gulden.application.jjack.clients.Socket</item>
	<item>de.gulden.application.jjack.clients.Gain</item>
	<item>de.gulden.application.jjack.clients.VU</item>
	<item>de.gulden.application.jjack.clients.Oscilloscope</item>
	<item>de.gulden.application.jjack.clients.Delay</item>
	<item>de.gulden.application.jjack.clients.Gate</item>
	<item>de.gulden.application.jjack.clients.Channel</item>
	<item>de.gulden.application.jjack.clients.Cable</item>
</tab>
<tab name="Swing">
	<item>javax.swing.JButton</item>
	<item>javax.swing.JCheckBox</item>
	<item>javax.swing.JComboBox</item>
	<item>javax.swing.JFormattedTextField</item>
	<item>javax.swing.JLabel</item>
	<item>javax.swing.JList</item>
	<item>javax.swing.JPasswordField</item>
	<item>javax.swing.JProgressBar</item>
	<item>javax.swing.JRadioButton</item>
	<item>javax.swing.JScrollBar</item>
	<item>javax.swing.JSlider</item>
	<item>javax.swing.JSpinner</item>
	<item>javax.swing.JTextArea</item>
	<item>javax.swing.JTextField</item>
	<item>javax.swing.JTextPane</item>
	<item>javax.swing.JToolBar</item>
	<item>javax.swing.JTree</item>
	<item>javax.swing.JTable</item>
	<item>javax.swing.JToggleButton</item>
</tab>
<tab name="Containers">
	<item>javax.swing.JApplet</item>
	<item>javax.swing.JEditorPane</item>
	<item>javax.swing.JInternalFrame</item>
	<item>javax.swing.JDialog</item>
	<item>javax.swing.JFrame</item>
	<item>javax.swing.JOptionPane</item>
	<item>javax.swing.JPanel</item>
	<item>javax.swing.JTabbedPane</item>
	<item>javax.swing.JWindow</item>
	<item>javax.swing.JColorChooser</item>
	<item>javax.swing.JFileChooser</item>
	<item>javax.swing.JScrollPane</item>
</tab>
<tab name="Menu">
	<item>javax.swing.JMenu</item>
	<item>javax.swing.JMenuBar</item>
	<item>javax.swing.JMenuItem</item>
	<item>javax.swing.JSeparator</item>
	<item>javax.swing.JCheckBoxMenuItem</item>
	<item>javax.swing.JRadioButtonMenuItem</item>
	<item>javax.swing.JPopupMenu</item>
</tab>
</palette>
